# Generated by Django 4.2.5 on 2024-04-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Ingredeints',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moops_app.ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products_videos/'),
        ),
    ]
