# Generated by Django 4.2.5 on 2024-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0004_product_ingredeints_alter_product_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
