# Generated by Django 4.2.5 on 2024-04-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0005_concerns'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='concerns',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moops_app.concerns'),
        ),
    ]
