# Generated by Django 4.2.5 on 2024-04-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0006_product_concerns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='swiper_slides/')),
                ('button_text', models.CharField(default='Button', max_length=100)),
                ('button_url', models.URLField(default='#')),
            ],
        ),
    ]
