# Generated by Django 4.2.5 on 2024-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0007_swiperslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_logos/')),
                ('alt_text', models.CharField(default='Client Logo', max_length=255)),
            ],
        ),
    ]
