# Generated by Django 4.2.5 on 2024-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0011_jumbotron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ingredeints',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='moops_app.ingredient'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='concerns',
        ),
        migrations.AddField(
            model_name='product',
            name='concerns',
            field=models.ManyToManyField(blank=True, to='moops_app.concerns'),
        ),
    ]
