# Generated by Django 4.2.5 on 2024-10-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0015_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
