# Generated by Django 4.2.5 on 2024-10-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
