# Generated by Django 4.2.5 on 2024-10-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0017_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredient_category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measurement', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredient_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moops_app.ingredientcategory')),
            ],
        ),
    ]
