# Generated by Django 4.2.5 on 2024-10-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0019_customizedorder_customizedproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moops_app.producttype'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moops_app.category'),
        ),
    ]
