# Generated by Django 4.2.5 on 2024-10-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0020_ingredients_product_type_alter_ingredients_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moops_app.category'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moops_app.ingredientcategory'),
        ),
    ]
