# Generated by Django 4.2.5 on 2024-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0024_order_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='timeline_images/')),
            ],
        ),
    ]
