# Generated by Django 4.2.5 on 2024-11-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0026_sectionone_sectionthree_sectiontwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='section_images/')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SectionOne',
        ),
        migrations.DeleteModel(
            name='SectionThree',
        ),
        migrations.DeleteModel(
            name='SectionTwo',
        ),
    ]
