# Generated by Django 4.2.5 on 2024-11-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0027_section_delete_sectionone_delete_sectionthree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyMilkFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='why_milk_icons/')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
