# Generated by Django 4.2.5 on 2024-11-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moops_app', '0028_whymilkfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_with_us/')),
            ],
        ),
    ]
