from django.urls import path,re_path
from  moops_app import views
from  django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve



urlpatterns = [
    path('',views.index,name='index'),
     path('product/<slug:slug>/', views.product_detail, name='product_detail'),

    path('product/review/<int:product_id>/', views.product_details, name='product_details'), 
    path('all_products',views.all_products,name='all_products'),
    path('admin_page',views.admin_page,name='admin_page'),
    path('login_page',views.login_page,name='login_page'),
    path('signup_page',views.signup_page,name='signup_page'),
    path('contact_page',views.contact_page,name='contact_page'),
    path('cart_page',views.cart_page,name='cart_page'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('add_product_type',views.add_product_type,name='add_product_type'),
    path('add_category',views.add_category,name='add_category'),
    path('category/<int:category_id>', views.category_view, name='category_view'),
    path('add_product',views.add_product,name='add_product'),
    path('p_delete_form/<int:pk>/',views.p_delete_form,name='p_delete_form'),
    path('usercreate',views.usercreate,name='usercreate'),
    path('signin',views.signin,name='signin'),
    path('logout',views.logout,name='logout'),
    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('add_blogs',views.add_blogs,name='add_blogs'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('manage_product_order',views.manage_product_order,name='manage_product_order'),
    path('delete_product_type/<int:delet_product_type>/',views.delete_product_type,name='delete_product_type'),
    path('edit_product_type/<int:edit_type>',views.edit_product_type,name='edit_product_type'),
    path('product_type/<int:product_typese>/', views.product_type_page, name='product_type_page'),  # Product type page
    path('add_ingredient',views.add_ingredient,name='add_ingredient'),
    path('delete_ingredient/<int:ingredints>/',views.delete_ingredient,name='delete_ingredient'),
    path('edit_ingredient/<int:edit>/',views.edit_ingredient,name='edit_ingredient'),
    path('ingredient_detail/<int:ingredients>/',views.ingredient_detail,name='ingredient_detail'),
    path('add_concerns',views.add_concerns,name='add_concerns'),
    path('delete_concerns/<int:concerns>/',views.delete_concerns,name='delete_concerns'),
    path('edit_concerns/<int:edit>/',views.edit_concerns,name='edit_concerns'),
    path('concern_detail/<int:concern>/',views.concern_detail,name='concern_detail'),
    path('add_slider_content',views.add_slider_content,name='add_slider_content'),
    path('edit_swiper_slide/<int:slide_id>/',views.edit_swiper_slide,name='edit_swiper_slide'),
    path('delete_swiper_slide/<int:slide_id>/',views.delete_swiper_slide,name='delete_swiper_slide'),
    path('add_find_logo',views.add_find_logo,name='add_find_logo'),
    path('edit_find_logo/<int:slide_id>/',views.edit_find_logo,name='edit_find_logo'),
    path('delete_find_logo/<int:slide_id>/',views.delete_find_logo,name='delete_find_logo'),
    path('edit_product/<int:product_id>/',views.edit_product,name='edit_product'),
    path('home_page_contents',views.home_page_contents,name='home_page_contents'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart/<int:pk>/', views.update_cart, name='update_cart'),
    path('delete_blogs/<int:delet_blogs>/',views.delete_blogs,name='delete_blogs'),
    path('add_to_cart_details/<int:pk>/', views.add_to_cart_details, name='add_to_cart_details'),
    path('add_hero_section',views.add_hero_section,name='add_hero_section'),
    path('edit_hero_section/<int:hero_id>/', views.edit_hero_section, name='edit_hero_section'),
    path('delete_hero_section/<int:hero_id>/',views.delete_hero_section,name='delete_hero_section'),
    path('add_jumbotron_section',views.add_jumbotron_section,name='add_jumbotron_section'),
    path('delete_jumbotron_section/<int:jumbotron>/',views.delete_jumbotron_section,name='delete_jumbotron_section'),
    path('edit_jumbotron_section/<int:hero_id>/',views.edit_jumbotron_section,name='edit_jumbotron_section'),
    path('add_mobile_slider_content',views.add_mobile_slider_content,name='add_mobile_slider_content'),
    path('delete_mobile_slide/<int:slide_id>/',views.delete_mobile_slide,name='delete_mobile_slide'),
    path('edit_mobile_slide/<int:slide_id>/',views.edit_mobile_slide,name='edit_mobile_slide'),
    path('add_video',views.add_video,name='add_video'),
    path('delete_video_section/<int:video>/',views.delete_video_section,name='delete_video_section'),
    path('edit_video/<int:pk>/',views.edit_video,name='edit_video'),
    path('about_us',views.about_us,name='about_us'),
    path('checkout_page',views.checkout_page,name='checkout_page'),
    path('user_orders',views.user_orders,name='user_orders'),
    path('admin_order_management',views.admin_order_management,name='admin_order_management'),
    path('add_ingredient_category',views.add_ingredient_category,name='add_ingredient_category'),
    path('add_ingredients',views.add_ingredients,name='add_ingredients'),
    path('add_customized_product',views.add_customized_product,name='add_customized_product'),
    path('customized_products_page',views.customized_products_page,name='customized_products_page'),
    path('add_customized_product_to_cart/<int:cp_id>/',views.add_customized_product_to_cart,name='add_customized_product_to_cart'),
    path('customized_cart_page',views.customized_cart_page,name='customized_cart_page'),
    path('place_customized_order',views.place_customized_order,name='place_customized_order'),
    path('update_quantity/<int:cart_item_id>/',views.update_quantity,name='update_quantity'),
    path('get_ingredients_by_type_and_category',views.get_ingredients_by_type_and_category,name='get_ingredients_by_type_and_category'),
    path('get_categories_by_product_type',views.get_categories_by_product_type,name='get_categories_by_product_type'),
    path('user_customize_orders',views.user_customize_orders,name='user_customize_orders'),
    path('manage_orders',views.manage_orders,name='manage_orders'),
    path('remove_from_customized_cart/<int:item_id>/',views.remove_from_customized_cart,name='remove_from_customized_cart'),
    path('edit_ingredient_category/<int:category_id>/',views.edit_ingredient_category,name='edit_ingredient_category'),
    path('delete_ingredient_category/<int:category_id>/',views.delete_ingredient_category,name='delete_ingredient_category'),
    path('edit_ingredients/<int:ingredient_id>/',views.edit_ingredients,name='edit_ingredients'),
    path('delete_ingredient/<int:ingredient_id>/',views.delete_ingredient,name='delete_ingredient'),
    path('contact_view',views.contact_view,name='contact_view'),
    path('contact_list',views.contact_list,name='contact_list'),
    path('delete_contact/<int:contact_id>/',views.delete_contact,name='delete_contact'),
    path('razorpay_callback/', views.razorpay_callback, name='razorpay_callback'),
    path('payment_success',views.payment_success,name='payment_success'),
    path('payment_failed',views.payment_failed,name='payment_failed'),
    path('process_order',views.process_order,name='process_order'),
    path('update_cart_quantity',views.update_cart_quantity,name='update_cart_quantity'),
    path('customized_razorpay_callback/', views.customized_razorpay_callback, name='customized_razorpay_callback'),
    path('add_timeline_event',views.add_timeline_event,name='add_timeline_event'),
    path('manage_sections',views.manage_sections,name='manage_sections'),
    path('edit_section/<int:section_id>/',views.edit_section,name='edit_section'),
    path('delete_section/<int:pk>/',views.delete_section,name='delete_section'),
    path('edit_why_milk/<int:feature_id>/',views.edit_why_milk,name='edit_why_milk'),
    path('delete_why_milk/<int:feature_id>/',views.delete_why_milk,name='delete_why_milk'),
    path('manage_why_milk',views.manage_why_milk,name='manage_why_milk'),
    path('manage_work_with_us/', views.manage_work_with_us, name='manage_work_with_us'),
    path('edit_work_with_us/<int:section_id>/', views.edit_work_with_us, name='edit_work_with_us'),
    path('delete_work_with_us/<int:section_id>/', views.delete_work_with_us, name='delete_work_with_us'),
]